//#include <ntifs.h>

#define YOUJAY_IOCTL_INDEX	0x2000

#define IOCTL_GetProcessNotify \
	CTL_CODE( FILE_DEVICE_UNKNOWN, YOUJAY_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_SetSyncEvent \
	CTL_CODE( FILE_DEVICE_UNKNOWN, YOUJAY_IOCTL_INDEX + 2, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_SetProcessStatus \
	CTL_CODE( FILE_DEVICE_UNKNOWN, YOUJAY_IOCTL_INDEX + 3, METHOD_BUFFERED, FILE_ANY_ACCESS )